# Generated by Django 2.2.6 on 2019-10-06 10:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TripSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('birth_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='birth date')),
                ('city', models.CharField(max_length=255)),
                ('number_license', models.CharField(max_length=255)),
                ('price', models.PositiveIntegerField(default=0)),
                ('sex', models.BooleanField(default=True)),
                ('present', models.BooleanField(default=False)),
                ('club_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chandeleur_app.Club')),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chandeleur_app.License')),
                ('trip_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chandeleur_app.TripSize')),
            ],
        ),
    ]
