# Generated by Django 2.2.6 on 2020-01-04 18:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chandeleur_app', '0003_auto_20191124_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredperson',
            name='birth_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='birth date'),
        ),
        migrations.AlterField(
            model_name='registeredperson',
            name='city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='registeredperson',
            name='club_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='chandeleur_app.Club'),
        ),
        migrations.AlterField(
            model_name='registeredperson',
            name='license',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='chandeleur_app.License'),
        ),
        migrations.AlterField(
            model_name='registeredperson',
            name='number_license',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
