# Generated by Django 2.2.6 on 2020-01-05 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chandeleur_app', '0004_auto_20200104_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeredperson',
            name='club_name',
        ),
        migrations.RemoveField(
            model_name='registeredperson',
            name='license',
        ),
        migrations.RemoveField(
            model_name='registeredperson',
            name='trip_size',
        ),
        migrations.RemoveField(
            model_name='registeredperson',
            name='user_in_charge',
        ),
        migrations.DeleteModel(
            name='Club',
        ),
        migrations.DeleteModel(
            name='License',
        ),
        migrations.DeleteModel(
            name='RegisteredPerson',
        ),
        migrations.DeleteModel(
            name='TripSize',
        ),
    ]
