# Generated by Django 2.2.6 on 2020-01-14 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chandeleur_app', '0006_club_license_registeredperson_tripsize'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registeredperson',
            old_name='number_license',
            new_name='license_number',
        ),
    ]
